name: signlanguage
description: "A real-time sign language detection Flutter application."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Essential for AI and Camera integration
  camera: ^0.11.0             # To access and control device cameras
  tflite_v2: ^1.0.0           # Optimized for running .tflite models
  permission_handler: ^11.3.1 # Handles runtime camera permissions
  
  # Firebase for data storage
  firebase_core: ^3.0.0       # Firebase core functionality
  cloud_firestore: ^5.0.0     # Cloud database
  uuid: ^4.0.0                # Generate unique session IDs
  intl: ^0.19.0               # Date formatting
  
  # Standard UI icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting for cleaner code
  flutter_lints: ^5.0.0
  
  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  # Enable Material Design
  uses-material-design: true

  # Register your AI assets so they are bundled with the app
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/NIDCD.webp

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/sign-language.png"
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "web/sign-language.png"
